# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 12, 15, 28, 13, 569000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
